<?php
require_once 'includes/auth_guard.php';
require_once 'includes/fpdf/fpdf.php';

$type = isset($_GET['type']) ? $_GET['type'] : '';
// Accept both ?id= and ?order_id= (view_invoice.php passes order_id)
$id = 0;
if (isset($_GET['id']) && intval($_GET['id']) > 0) {
    $id = intval($_GET['id']);
} elseif (isset($_GET['order_id']) && intval($_GET['order_id']) > 0) {
    $id = intval($_GET['order_id']);
}

// 'invoice' is an alias for 'sales_order' — same data, just titled differently
if ($type === 'invoice') {
    $type = 'sales_order';
}

if (!$type || !$id) {
    die("Invalid request parameters.");
}

class PDF extends FPDF
{
    function Header()
    {
        // Logo / Title
        $this->SetFont('Arial', 'B', 24);
        $this->SetTextColor(109, 74, 255); // Primary color
        $this->Cell(0, 10, 'Agile Inventory', 0, 1, 'L');
        $this->SetFont('Arial', '', 10);
        $this->SetTextColor(107, 114, 128);
        $this->Cell(0, 6, '123 Enterprise Way, Suite 100', 0, 1, 'L');
        $this->Cell(0, 6, 'Tech District, Metropolis', 0, 1, 'L');
        $this->Cell(0, 6, 'Phone: (555) 123-4567', 0, 1, 'L');
        $this->Ln(10);
        $this->SetDrawColor(229, 231, 235);
        $this->Line(10, $this->GetY(), 200, $this->GetY());
        $this->Ln(10);
    }

    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(156, 163, 175);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . ' /{nb} | Generated by Agile Inventory System', 0, 0, 'C');
    }
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 11);

if ($type === 'sales_order' || $type === 'receipt') {
    // Fetch Sales Order
    $stmt = $conn->prepare("
        SELECT so.*, c.customer_name, c.email, c.contact_number AS phone, c.address 
        FROM sales_orders so 
        LEFT JOIN customers c ON so.customer_id = c.id 
        WHERE so.id = ?
    ");
    $stmt->bind_param("i", $id);
    $stmt->execute();
    $so = $stmt->get_result()->fetch_assoc();
    $stmt->close();

    if (!$so)
        die("Order not found.");

    // Header Details
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->SetTextColor(17, 24, 39);
    $doc_title = ($type === 'receipt') ? 'TAX RECEIPT' : 'SALES INVOICE';
    $pdf->Cell(100, 10, $doc_title, 0, 0);

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->Cell(90, 10, 'Reference: ' . $so['order_id_str'], 0, 1, 'R');

    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor(75, 85, 99);
    $pdf->Cell(100, 6, 'Date: ' . date('F j, Y', strtotime($so['order_date'])), 0, 0);
    $status_text = 'Status: ' . strtoupper($so['status']);
    $pdf->Cell(90, 6, $status_text, 0, 1, 'R');
    $pdf->Ln(10);

    // Bill To
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->SetTextColor(17, 24, 39);
    $pdf->Cell(0, 8, 'Bill To:', 0, 1);
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor(75, 85, 99);
    $c_name = $so['customer_name'] ?? 'Walk-in Customer';
    $pdf->Cell(0, 6, $c_name, 0, 1);
    if (!empty($so['email']))
        $pdf->Cell(0, 6, $so['email'], 0, 1);
    if (!empty($so['phone']))
        $pdf->Cell(0, 6, $so['phone'], 0, 1);
    $pdf->Ln(10);

    // Table Header
    $pdf->SetFillColor(243, 244, 246);
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->SetTextColor(55, 65, 81);
    $pdf->Cell(80, 10, 'Item Description', 1, 0, 'L', true);
    $pdf->Cell(30, 10, 'Qty', 1, 0, 'C', true);
    $pdf->Cell(40, 10, 'Unit Price', 1, 0, 'C', true);
    $pdf->Cell(40, 10, 'Total', 1, 1, 'C', true);

    // Items
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor(17, 24, 39);

    $items_stmt = $conn->prepare("SELECT soi.*, p.product_name FROM sales_order_items soi JOIN products p ON soi.product_id = p.id WHERE soi.sales_order_id = ?");
    $items_stmt->bind_param("i", $id);
    $items_stmt->execute();
    $items = $items_stmt->get_result();

    $subtotal = 0;
    while ($item = $items->fetch_assoc()) {
        $pdf->Cell(80, 10, substr($item['product_name'], 0, 45), 1);
        $pdf->Cell(30, 10, $item['quantity'], 1, 0, 'C');
        $pdf->Cell(40, 10, '$' . number_format($item['unit_price'], 2), 1, 0, 'R');
        $pdf->Cell(40, 10, '$' . number_format($item['subtotal'], 2), 1, 1, 'R');
        $subtotal += $item['subtotal'];
    }
    $items_stmt->close();

    // Financial Summary
    $pdf->Ln(5);
    $pdf->SetFont('Arial', '', 10);

    $pdf->Cell(110, 8, '', 0, 0);
    $pdf->Cell(40, 8, 'Subtotal:', 0, 0, 'R');
    $pdf->Cell(40, 8, '$' . number_format($subtotal, 2), 0, 1, 'R');

    if (isset($so['discount_amount']) && $so['discount_amount'] > 0) {
        $pdf->Cell(110, 8, '', 0, 0);
        $pdf->SetTextColor(239, 68, 68); // Red for discount
        $disc_label = 'Discount';
        if (!empty($so['applied_discount_code']))
            $disc_label .= ' (' . $so['applied_discount_code'] . ')';
        $pdf->Cell(40, 8, $disc_label . ':', 0, 0, 'R');
        $pdf->Cell(40, 8, '-$' . number_format($so['discount_amount'], 2), 0, 1, 'R');
        $pdf->SetTextColor(17, 24, 39);
    }

    if (isset($so['tax_amount']) && $so['tax_amount'] > 0) {
        $pdf->Cell(110, 8, '', 0, 0);
        $pdf->Cell(40, 8, 'Tax:', 0, 0, 'R');
        $pdf->Cell(40, 8, '$' . number_format($so['tax_amount'], 2), 0, 1, 'R');
    }

    if (isset($so['delivery_charge']) && $so['delivery_charge'] > 0) {
        $pdf->Cell(110, 8, '', 0, 0);
        $pdf->Cell(40, 8, 'Delivery Charge:', 0, 0, 'R');
        $pdf->Cell(40, 8, '$' . number_format($so['delivery_charge'], 2), 0, 1, 'R');
    }

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->Cell(110, 10, '', 0, 0);
    $pdf->Cell(40, 10, 'Grand Total:', 0, 0, 'R');
    $pdf->Cell(40, 10, '$' . number_format($so['total_amount'], 2), 0, 1, 'R');

    // Payment Info
    $pdf->Ln(10);
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(0, 8, 'Payment Information:', 0, 1);
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor(75, 85, 99);

    $p_stmt = $conn->prepare("SELECT * FROM payments_received WHERE notes LIKE ?");
    $like_str = "%" . $so['order_id_str'] . "%";
    $p_stmt->bind_param("s", $like_str);
    $p_stmt->execute();
    $payment = $p_stmt->get_result()->fetch_assoc();
    $p_stmt->close();

    if ($payment) {
        $pdf->Cell(0, 6, 'Method: ' . $payment['payment_method'], 0, 1);
        $pdf->Cell(0, 6, 'Amount Paid: $' . number_format($payment['amount'], 2), 0, 1);
        $pdf->Cell(0, 6, 'Transaction Ref: ' . $payment['payment_ref_str'], 0, 1);
    } else {
        $pdf->Cell(0, 6, 'Status: Awaiting Payment', 0, 1);
    }

    // Output
    $filename = "Invoice_" . $so['order_id_str'] . ".pdf";
    $pdf->Output('I', $filename);
} else {
    die("Export type not supported.");
}
?>